### ISSUE TITLE
Chrome CSS Fix

### ISSUE THREAD

**Issue by sheldonlendrum** [julesjanssen/chosen#28]
In Chrome(Webkit) the UL in the dropdown is floating off to the left. Hidden ..

Here is a fix;

``` css
.chzn-container .chzn-results {
    /* webkit fix */
    display: block;
    clear: left;
    /* end fix */
    margin: 0 4px 4px 0;
    max-height: 190px;
    padding: 0 0 0 4px;
    position: relative;
    overflow-x: hidden;
    overflow-y: auto;
}
```
