### ISSUE TITLE
Bug when selecting item - deselect it and select it again

### ISSUE THREAD

**Issue by Adidi** [julesjanssen/chosen#38]
If you select it in the second time the item appear in the list (but can't be selected) - 
this is happens because when you deselct an item there is set style block and when you select it again the display block override the display none in result-selected css rule set to that li:

the fix is in line 591 instead 

``` javascript
result.removeClass("result-selected").addClass("active-result").setStyle('display', 'block');
```

remove the set style display block

``` javascript
result.removeClass("result-selected").addClass("active-result");
```

Because I don't understand why there is need to set it display block if you remove the result-selected css rule.

Alternatively you can set the css rule:

``` css
.chzn-container-multi .chzn-drop .result-selected {
  display: none;
}
```

to 

``` css
.chzn-container-multi .chzn-drop .result-selected {
  display: none !important;
}
```
